--
-- Reverse-engineered from the committed northwind.sqlite (which realises the DuckDB blueprint).
-- Regenerated by: sqlite3 northwind.sqlite ".mode insert <table>" "SELECT * FROM <table>;"
-- Rebuild the binary with the :sqlite:SqliteNorthwindScript task.
--

INSERT INTO region VALUES(1,'Eastern');
INSERT INTO region VALUES(2,'Western');
INSERT INTO region VALUES(3,'Northern');
INSERT INTO region VALUES(4,'Southern');
