--
-- Reverse-engineered from the committed northwind.sqlite (which realises the DuckDB blueprint).
-- Regenerated by: sqlite3 northwind.sqlite ".mode insert <table>" "SELECT * FROM <table>;"
-- Rebuild the binary with the :sqlite:SqliteNorthwindScript task.
--

INSERT INTO check_type VALUES(1,32000,2147483647,9223372036854775807,12345.67890000000079,1.618033988749000062,1.618033988749000062,1,1,'Y','2026-05-17','14:30:45','2026-05-17 14:30:45');
