--
-- Reverse-engineered from the committed northwind.sqlite (which realises the DuckDB blueprint).
-- Regenerated by: sqlite3 northwind.sqlite ".mode insert <table>" "SELECT * FROM <table>;"
-- Rebuild the binary with the :sqlite:SqliteNorthwindScript task.
--

INSERT INTO categories VALUES(11,'Food','All food',X'',11,NULL);
INSERT INTO categories VALUES(12,'Chilled Food','Chilled food',X'',11,11);
INSERT INTO categories VALUES(13,'Drugstore','Drugstore',X'',13,NULL);
INSERT INTO categories VALUES(14,'Pet supplies','Pet supplies',X'',14,NULL);
INSERT INTO categories VALUES(1,'Beverages','Soft drinks, coffees, teas, beers, and ales',X'',11,11);
INSERT INTO categories VALUES(2,'Condiments','Sweet and savory sauces, relishes, spreads, and seasonings',X'',11,11);
INSERT INTO categories VALUES(3,'Confections','Desserts, candies, and sweet breads',X'',11,11);
INSERT INTO categories VALUES(4,'Dairy Products','Cheeses',X'',11,12);
INSERT INTO categories VALUES(5,'Grains/Cereals','Breads, crackers, pasta, and cereal',X'',11,11);
INSERT INTO categories VALUES(6,'Meat/Poultry','Prepared meats',X'',11,12);
INSERT INTO categories VALUES(7,'Produce','Dried fruit and bean curd',X'',11,11);
INSERT INTO categories VALUES(8,'Seafood','Seaweed and fish',X'',11,12);
INSERT INTO categories VALUES(9,'Tissue','Toiletpaper, Kitchen towel, Cosmetic pliers',X'',13,13);
INSERT INTO categories VALUES(10,'Hygienearticles','Deodorant, soap, shaving foam',X'',13,13);
