FIND order_details d, d orders o, d products p, o customers c
FILTER o.order_date BETWEEN "2023-01-01" AND "2023-12-31" AND c.company_name LIKE 'C%'
FETCH
o.order_id ASC,
p.product_name ASC,
c.company_name,
to_decimal(d.unit_price, 18, 6),
d.quantity,
to_decimal(to_decimal(d.unit_price, 18, 6) * to_decimal(d.quantity, 18, 6), 18, 6) product_total,
sum(to_decimal(to_decimal(d.unit_price, 18, 6) * to_decimal(d.quantity, 18, 6), 18, 6)) OVER(PARTITION o.order_id ORDER o.order_id) order_total
